# Generated by Django 2.2 on 2019-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=20, null=True)),
                ('field2', models.IntegerField(default=0)),
                ('field3', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
